name: publish-package
on:
  pull_request:
    branches:
      - main

jobs:
  publish-package:
    # if: ${{contains(github.base_ref, 'create-pull-request/')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"
          echo "${{ github.ref_type }}"
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/setup-node@v2
    #     with:
    #       node-version: '14'
    #   - run: |
    #       yarn install
    #       yarn lerna:new-version
    #       yarn lerna:publish
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
