name: publish-package
on:
  pull_request:
    branches:
      - main

jobs:
  publish-package:
    # if: ${{contains(github.base_ref, 'create-pull-request/')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo "${{ github.ref }}"
        echo "${{ github.ref_name }}"
        echo "${{ github.ref_type }}"
        echo ${{ github.event.pull_request.title }}
        echo "${{ steps.branch-name.outputs.current_branch }}"
        echo "${{ github.event.pull_request.head.ref }}"

    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/setup-node@v2
    #     with:
    #       node-version: '14'
    #   - run: |
    #       yarn install
    #       yarn lerna:new-version
    #       yarn lerna:publish
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
