name: publish-package
on:
  push:
    branches:
      - 'create-pull-request/**'

jobs:
  publish-package:
    name: publish package
    run: echo 'ggwp'
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/setup-node@v2
    #     with:
    #       node-version: '14'
    #   - run: |
    #       yarn install
    #       yarn lerna:new-version
    #       yarn lerna:publish
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
